python ../python/split.py asw.editready.txt asw
python ../python/split.py ceu.editready.txt ceu
python ../python/split.py chb.editready.txt chb
python ../python/split.py chd.editready.txt chd
python ../python/split.py jpt.editready.txt jpt
python ../python/split.py lwk.editready.txt lwk
python ../python/split.py tsi.editready.txt tsi
python ../python/split.py yri.editready.txt yri
python ../python/split.py african.editready.txt african
python ../python/split.py eastasian.editready.txt eastasian
python ../python/split.py european.editready.txt european
